### PR TITLE
Finetune Design on Homepage && Tidy Up Styles and Markup

### PR DESCRIPTION
**Pull request by ovlb**
Started working on the homepage, updated the events section so far. Feedback for this very welcome.

Also removed unnecessary wrapper elements, flattening the HTML strutcture as an effect. Accompanying work is done to the site’s CSS, aiming to reduce nesting and having styles cascade better. 

### Open

- [x] Update news section on homepage
- [ ] Clearer headline styles for sections
- [ ] Break all styles into partials
- [ ] Better responsive typography and spacing to make reading more pleasant

### CODE REVIEW

**Comment by shushugah** [comment]
I love what you did here! it's much sharper, especially the events! I would even merge this already, but noted two breaking 
changes brought in this PR s

- [ ] Fix trailing /events (blocked by footer) at https://deploy-preview-99--techworkersberlin.netlify.app/events
- [x] Fix distorted author images inside the /news and homepage preview (screenshot included below)

but it changes the "avatars" of in the /news entries, distorting them slightly!  

<details>
<summary>Click to see image</summary>

Screenshot 2020-09-27 at 22 57 13 -->
</details>

**Comment by ovlb** [comment]
@shushugah Thanks!

Noticed the images too, but it was getting late and I still don’t fully understand why this is happening. 
The «effect» is visible on the current homepage already, albeit not so extreme. But I need to revamp the CSS for those teasers anyway as there is an uncleared float on the image, which sometimes leads to this kind of effect:

<details>
<summary>Click to see image</summary>

Screen Shot 2020-09-28 at 08 20 41
</details>

**Comment by shushugah** [comment]
can you rebase off of `develop` branch? I made a breaking change, when I removed node_modules, my bad >.>

**Comment by ovlb** [comment]
@shushugah Done. I think the PR is mergeable as is. I’ll open new ones for further work (eg. styling the press area).

**Pull request merged**
